### ISSUE TITLE
TypeError: Cannot read property 'behavior' of undefined

### ISSUE THREAD

**Issue by rsrini7** [rundis/LightTable-Groovy#21]
I am getting below error in lighttable after installing groovy plugin.

\AppData\Roaming\LightTable\plugins\Groovy\groovy_compiled.js : TypeError: Cannot read property 'behavior' of undefined

TypeError: Cannot read property 'behavior' of undefined
    at eval (C:%5CUsers%5Crsrini%5CAppData%5CRoaming%5CLightTable%5Cplugins%5CGroovy%5Cgroovy_compiled.js:780:50)
    at eval (native)
    at c (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:21436:41)
    at a (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:21444:18)
    at Function.lt.objs.plugins.__BEH__load_js (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:29874:33)
    at c (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20339:76)
    at a (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20363:18)
    at c (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20417:169)

**Comment by rsrini7** [comment]
Invalid behavior: :lt.plugins.groovy/connect

Now, I am getting below error: 

Error: spawn UNKNOWN
  at exports._errnoException (util.js:837:11)
  at ChildProcess.spawn (internal/child_process.js:298:11)
  at exports.spawn (child_process.js:351:9)
  at lt.objs.proc.simple_spawn_STAR_ (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:31415:216)
  at file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:31460:82
  at [object Object].cljs.core.LazySeq.sval (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:5561:40)
  at [object Object].cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:5571:8)
  at cljs.core._seq (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:2311:14)
  at cljs.core.seq (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:2824:27)
  at b (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:12224:25)
  at a (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:12243:18)
  at b (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:12255:21)
  at a (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:12263:18)
  at lt.objs.proc.exec (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:31434:231)
  at run_groovy (C:%5CUsers%5Crsrini%5CAppData%5CRoaming%5CLightTable%5Cplugins%5CGroovy%5Cgroovy_compiled.js:875:26)
  at notify (C:%5CUsers%5Crsrini%5CAppData%5CRoaming%5CLightTable%5Cplugins%5CGroovy%5Cgroovy_compiled.js:895:31)
  at check_all (C:%5CUsers%5Crsrini%5CAppData%5CRoaming%5CLightTable%5Cplugins%5CGroovy%5Cgroovy_compiled.js:901:88)
  at try_connect (C:%5CUsers%5Crsrini%5CAppData%5CRoaming%5CLightTable%5Cplugins%5CGroovy%5Cgroovy_compiled.js:903:575)
  at Function.__BEH__connect (C:%5CUsers%5Crsrini%5CAppData%5CRoaming%5CLightTable%5Cplugins%5CGroovy%5Cgroovy_compiled.js:992:38)
  at c (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
  at a (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
  at c (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20339:76)
  at a (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20363:18)
  at a (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20374:34)
  at b (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20378:14)
  at lt.objs.dialogs.dir (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:30206:253)
  at eval (C:%5CUsers%5Crsrini%5CAppData%5CRoaming%5CLightTable%5Cplugins%5CGroovy%5Cgroovy_compiled.js:1022:399)
  at HTMLLIElement.<anonymous> (file:///D:/DevTools/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:32898:108)

**Comment by rundis** [comment]
Sorry, but I haven't managed to find time to keep the plugin up to date with the latest Light Table versions and Groovy (and Gradle) versions. Plugin needs a new maintainer to keep it alive.
